ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations: 
  hosts:
    - host: homarr.local
      paths:
        - path: /
          pathType: Prefix
persistence:
  homarrDatabase:
    enabled: true
    name: "homarr-database"
    storageClassName: "local-path"
    accessMode: "ReadWriteOnce"
    size: "1Gi"
    mountPath: "/appdata"
env:
  TZ: "Europe/Warsaw"
